---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: catalog-dep 
  labels:
    env: dev 
specs:
  replicas: 3
  selectors:
    matchLabels: 
      env: dev 
  template:
    metadata:
      labels:
        env: dev 
    spec: 
      containers:
        - name: catalog-pod 
          image: mehulbisen/catalog:v1 
          ports:
            - containerPort: 80
...
---
apiVersion: v1
kind: Service 
metadata:
  name: catalog-svc 
  labels:
    env: dev 
spec:
  type: ClusterIP
  selector:
    env: dev 
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP 
...